### ISSUE TITLE
win7_64  tbb link error

### ISSUE THREAD

**Issue by bolunfeng** [oneapi-src/oneTBB#174] opened 2019-08-16 06:17 UTC
hello:
make  compiler=gcc arch=intel64 tbb_root=%TBB_ROOT% extra_inc="..\..\tbb_static.inc" tbb_os=windows   tbb_build_prefix=tbb tbb_build_dir=%TBB_ROOT%\..\..\lib\%OSTYPE%\%COMPILER%\%BUILDTYPE%\ 

at last,I get the error:
../../lib/win/gcc/debug/tbb_debug/libtbb_debug.a(task.o): duplicate section `.rdata$_ZTIN3tbb4taskE[_ZTIN3tbb4taskE]' has different size
../../lib/win/gcc/debug/tbb_debug/libtbb_debug.a(arena.o): duplicate section `.rdata$_ZTIN3tbb4taskE[_ZTIN3tbb4taskE]' has different size
../../lib/win/gcc/debug/tbb_debug/libtbb_debug.a(scheduler.o): duplicate section `.rdata$_ZTIN3tbb4taskE[_ZTIN3tbb4taskE]' has different size
../../lib/win/gcc/debug/tbb_debug/libtbbmalloc_debug.a(tbbmalloc.o): In function `DllMain':

**Comment by alexey-katranov** [comment] 2020-08-13 13:45
Duplicate of https://github.com/msys2/MINGW-packages/issues/3904 and https://github.com/oneapi-src/oneTBB/issues/246

**Closed by alexey-katranov** 2020-08-13 13:45 UTC
