### ISSUE TITLE
Node `try_put` should have rvalue overload

### ISSUE THREAD

**Issue by jeremyong** [oneapi-src/oneTBB#235] opened 2020-03-31 04:37 UTC
It is impossible to pass move-only types to a flow graph node via `try_put` due to a copy-constructor in the implementation of the flow graph item buffer [here](https://github.com/oneapi-src/oneTBB/blob/tbb_2020/include/tbb/internal/_flow_graph_item_buffer_impl.h#L174).

It seems reasonable to perform a move if `try_put` was invoked on an rvalue which can be determined with an overload of `try_put` with signature `bool try_put(T&& t)`.

An alternative solution is to check the trait `std::is_copy_constructible_v<T>` for truthiness. If false, attempt a move constructor instead.

I'm not sure what version of C++ is targeted, but if 17 is targeted, constexpr could be used. Otherwise, SFINAE can be used by lifting the copy/move construction to a separate template helper function.

**Comment by alexey-katranov** [comment] 2020-03-31 06:50
It is quite difficult to enable move support everywhere because some nodes (e.g. `broadcast_node`) are supposed to forward messages to multiple successors. In other word, in some cases copy semantics is unavoidable.
In any case, we can consider where move semantics is applicable and extend such cases (e.g. input of function nodes and buffering nodes). Thank you for the idea.

**Comment by aleksei-fedotov** [comment] 2020-04-06 12:38
Related to #138.

**Comment by aleksei-fedotov** [comment] 2020-04-06 12:42
Closing as a duplicate of the above-mentioned issue. The status will be tracked there.

**Closed by aleksei-fedotov** 2020-04-06 12:42 UTC
