### ISSUE TITLE
(multi)function_node tasks are not executed without graph.wait_for_all()

### ISSUE THREAD

**Issue by lzhangzz** [oneapi-src/oneTBB#218] opened 2020-02-25 14:09 UTC
Hi, 

When using TBB flow graph, I encounter a problem that some tasks of multifunction_node are not executed until wait_for_all() is called. 

Minimal code to reproduce the problem is attached (I tested gcc-4.9 & gcc-9, with TBB 2020.1, on Ubuntu 14.04/16.04, and CentOS7 with TBB 2018.2)
```C++
#include <iostream>
#include <tuple>
#include <atomic>
#include <thread>
#include "tbb/flow_graph.h"

using namespace tbb::flow;
typedef multifunction_node<int, tbb::flow::tuple<int>> multi_node;

// simple mechanism to control resource consumption
std::atomic<int> g_finished{0};

// Does nothing, forward it's input immediately
struct MultiBodyBypass {
  void operator()(const int &i, multi_node::output_ports_type &op) {
    std::get<0>(op).try_put(i);
  }
};

// Does random amount of work before forwarding
struct MultiBodyPayload {
  void operator()(const int &i, multi_node::output_ports_type &op) {
    payload();
    std::get<0>(op).try_put(i);
    ++g_finished;
  }
  static void payload() {
    int n = rand() % 100000;
    int sum = 0;
    for (int i = 0; i < n; ++i)
      sum += n;
  }
};

int main() {
  graph g;

  multi_node node1(g, serial, MultiBodyBypass());
  multi_node node2(g, serial, MultiBodyPayload());

  make_edge(output_port<0>(node1), node2);

  for(int i = 0; i < 100000; ++i) {
    if (!node1.try_put(i))
      abort(); // abort on unlikely failure
    int j;
    // limit num of processing items to 512
    while ((j = g_finished.load()) < i - 512) {
      std::cout << j << "\n";
      std::this_thread::yield();
    }
  }
  
  g.wait_for_all();

  std::cout << g_finished << "\n";

  return 0;
}
```
Here very likely the program stuck in the while loop printing the same number forever, like some of the items we put in the graph disappeared (they even didn't reach node1). The parameters may need tuning to reproduce the problem on different systems. We have checked that, at runtime,  the max_concurrency of the arena of the graph is 16, the number of our logical cores.

If we remove the limitation on resource (remove the while loop so g.wait_for_all() can be reached) or we call wait_for_all directly in the while loop (which is not feasible for our application), the program ends normally.

~~BTW, The problem is not observed with function_node. (But we really need the explicit try_put of multifunction_node)~~

As I am not very familiar with the code of TBB,  I failed to find out what happens under the hood. Any ideas on the cause of the problem or how to avoid it are much appreciated.

I wonder if this is related to #86 

Thanks

**Comment by lzhangzz** [comment] 2020-02-26 04:55
Hi,

After more experiments, I found that all 4 combinations of multifunction_node/function_node of node1/node2 in the reproducer above have the problem. 

The updated version
```C++


#include <iostream>
#include <tuple>
#include <atomic>
#include <thread>
#include "tbb/flow_graph.h"

using namespace tbb::flow;
typedef multifunction_node<int, tbb::flow::tuple<int>> multi_node;

// simple mechanism to control resource consumption
std::atomic<int> g_finished{0};

// random payload
void payload() {
  int n = rand() % 100000;
  int sum = 0;
  for (int i = 0; i < n; ++i)
    sum += n;
}

// Does nothing, forward it's input immediately
struct MultiBodyBypass {
  void operator()(const int &i, multi_node::output_ports_type &op) {
    std::get<0>(op).try_put(i);
  }
};

// Does random amount of work before forwarding
struct MultiBodyPayload {
  void operator()(const int &i, multi_node::output_ports_type &op) {
    payload();
    std::get<0>(op).try_put(i);
    ++g_finished;
  }
};

#define NODE1_MULTI true
#define NODE2_MULTI true

int main() {
  graph g;
#if NODE1_MULTI && NODE2_MULTI
  multi_node node1(g,serial, MultiBodyBypass());
  multi_node node2(g,serial, MultiBodyPayload());
  make_edge(output_port<0>(node1), node2);
#elif !NODE1_MULTI && NODE2_MULTI
  function_node<int, int> node1(g, serial, [](const int& x){return x;});
  multi_node node2(g,serial, MultiBodyPayload());
  make_edge(node1, node2);
#elif NODE1_MULTI && !NODE2_MULTI
  multi_node node1(g,serial, MultiBodyBypass());
  function_node<int, int> node2(g, serial, [](const int& x){
    payload(); ++g_finished; return x;
  });
  make_edge(output_port<0>(node1), node2);
#elif !NODE1_MULTI && !NODE2_MULTI
  function_node<int, int> node1(g, serial, [](const int& x){return x;});
  function_node<int, int> node2(g, serial, [](const int& x){
    payload(); ++g_finished; return x;
  });
  make_edge(node1, node2);
#endif

  for(int i = 0; i < 100000; ++i) {
    if (!node1.try_put(i))
      abort(); // abort on unlikely failure
    int j;
    // limit num of processing items to 512
    while ((j = g_finished.load()) < i - 512) {
      std::cout << j << "\n";
      std::this_thread::yield();
    }
  }
  g.wait_for_all();
  std::cout << g_finished << "\n";
  return 0;
}
```

**Comment by lzhangzz** [comment] 2020-02-28 11:35
After more tests, I have some interesting findings, 

1. the problem only occurs when the 2 nodes are serial.
2. when node1.try_put() is enqueued by graph.run(), or the enqueue() method of an explicit arena associated with the graph, the problem is gone.
3. tried calling node1.try_put() with the execute() method of an explicit arena, the problem exists even with reserved_for_master of the arena is set to 0.

**Comment by aleksei-fedotov** [comment] 2020-03-13 09:02
TBB does not guarantee concurrent execution of tasks. Please see the 2nd caution on [the page in the documentation](https://www.threadingbuildingblocks.org/docs/help/hh_goto.htm?index.htm#reference/flow_graph/graph_cls.html). Therefore, method "graph::wait_for_all()" must be called in order to make the progress.

BTW, I was not able to reproduce the hang. So, it is really up to TBB library how to execute the stuff.

**Comment by aleksei-fedotov** [comment] 2020-03-24 07:51
Since this is expected behavior I propose closing this issue. Interested people could always reopen it if they think there is something to discuss further.

**Closed** 2020-03-24 09:23 UTC
