### ISSUE TITLE
CMake+Ninja+clang: warning as error: argument unused during compilation: '-MD' ('-MMD')

### ISSUE THREAD

**Issue by JonForShort** [oneapi-src/oneTBB#364] opened 2021-03-19 01:47 UTC
Hi, I am attempting to build `tbb` with CMake using android NDK version `22.0.7026061`, but getting some compilation failures.

```
Clang Version
Android (6875598, based on r399163b) clang version 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315dfbea7c137aa2e6d362dbb457e388158d)
```

```
/opt/android/sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=armv7-none-linux-androideabi29 --gcc-toolchain=/opt/android/sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/opt/android/sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/linux-x86_64/sysroot  -DTBB_USE_DEBUG -D__TBB_BUILD -I../../../../src/main/cpp/tbb/src/tbb/../../include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security   -O0 -fno-limit-debug-info  -fPIC   -MMD -Wall -Wextra -Werror -std=c++1z -MD -MT src/main/cpp/tbb/src/tbb/CMakeFiles/tbb.dir/address_waiter.cpp.o -MF src/main/cpp/tbb/src/tbb/CMakeFiles/tbb.dir/address_waiter.cpp.o.d -o src/main/cpp/tbb/src/tbb/CMakeFiles/tbb.dir/address_waiter.cpp.o -c ../../../../src/main/cpp/tbb/src/tbb/address_waiter.cpp

clang++: error: argument unused during compilation: '-MD' [-Werror,-Wunused-command-line-argument]
```

I tried setting `TBB_STRICT` to `OFF` which allows me to get further in the build process, but still fails.

```
/opt/android/sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=armv7-none-linux-androideabi29 --gcc-toolchain=/opt/android/sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/opt/android/sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/linux-x86_64/sysroot  -DTBB_USE_DEBUG -D__TBB_BUILD -I../../../../src/main/cpp/tbb/src/tbb/../../include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat =format-security   -O0 -fno-limit-debug-info  -fPIC   -MMD -Wall -Wextra -std=c++14 -MD -MT src/main/cpp/tbb/src/tbb/CMakeFiles/tbb.dir/address_waiter.cpp.o -MF src/main/cpp/tbb/src/tbb/CMakeFiles/tbb.dir/address_waiter.cpp.o.d -o src/main/cpp/tbb/src/tbb/CMakeFiles/tbb.dir/address_waiter.cpp.o -c ../../../../src/main/cpp/tbb/src/tbb/address_waiter.cpp

clang++: error: no such file or directory: '=format-security'
```

My understanding is that tbb does support Android with Clang.  The way I am including tbb into my project is to simply add tbb to my CMake project using "add_subdirectory", and then building the "tbb" target.

```
cmake_minimum_required(VERSION 3.10.2)

set(BUILD_SHARED_LIBS ON)

add_subdirectory(tbb)
```

Is this the correct way to integrate tbb into Android?

Thanks!

**Comment by AlexVeprev** [comment] 2021-03-19 17:01
@JonForShort, could you please provide cmake command you use for the build?

I tried the following one with oneTBB from master branch:
`cmake -DCMAKE_TOOLCHAIN_FILE=/tmp/android-ndk-r22/build/cmake/android.toolchain.cmake -DTBB_TEST=OFF -DANDROID_STL=c++_shared -DANDROID_PLATFORM=android-30 -DANDROID_ABI=arm64-v8a ..`
then `make` and it works fine.

With `-DANDROID_ABI=armeabi-v7a` it works as well.

**Comment by JonForShort** [comment] 2021-03-19 18:00
Thanks @AlexVeprev for checking this for me.  It must be a local environment issue then.  I'll double check this on my side.

**Comment by AlexVeprev** [comment] 2021-03-19 19:22
@JonForShort, I was able to reproduce the error with `Ninja` while the same options work with `Make`.

**Comment by AlexVeprev** [comment] 2021-03-19 19:32
I've tried to play with cmake and found that `-MD` (that causes the failure) comes from this line: https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/Compiler/GNU.cmake#L51

I've tried to comment this line and got successful build:
```
> ninja
[39/39] Linking CXX shared library clang_11.0_cxx11_64_relwithdebinfo/libtbb.so
```

**Comment by AlexVeprev** [comment] 2021-03-19 19:44
Different CMake behavior for Ninja and Make is not straightforward for me yet.

There is another issue on oneTBB side with `TBB_STRICT=OFF` that you faced above: `-Werror=format-security` is added by default in your case, `TBB_STRICT=OFF` triggers removal of `-Werror` from passed options while `=format-security` is not removed.

**Comment by JonForShort** [comment] 2021-03-19 19:56
Hi @AlexVeprev , oh great.  Thanks for tracking down the issue.  I was able to build successfully using the ```Make``` generator.  Unfortunately ```Ninja``` is the default one for Android so I don't know how easy it will be to switch in my builds.

Regarding commenting out ```-MD```, can you explain a bit more about how you were able to do that? I see in the ```Clang``` compiler cmake file that ```-MMD``` is set but I don't see anywhere ```-MD``` is set.

https://github.com/oneapi-src/oneTBB/blob/master/cmake/compilers/Clang.cmake#L17

**Comment by AlexVeprev** [comment] 2021-03-19 21:09
I've modified the file in my cmake installation: `<prefix>/share/cmake-<ver>/Modules/Compiler/GNU.cmake`, for sure it's a very rough workaround.

**Comment by AlexVeprev** [comment] 2021-03-19 21:35
@JonForShort, I've checked it more deeply and now have a better workaround for you: comment out the line with `-MMD` just as you had found: https://github.com/oneapi-src/oneTBB/blob/master/cmake/compilers/Clang.cmake#L17

Explanation: oneTBB explicitly adds `-MMD` while CMake with Ninja adds `-MD` to compilation string, these options seems to be similar, so as I understand if one is set another is ignored with the warning (as error).

**Comment by JonForShort** [comment] 2021-03-19 23:43
Thanks @AlexVeprev for all the help with this issue.  I have confirmed this work-around works well on my end.  Please feel free to close this issue.

**Comment by AlexVeprev** [comment] 2021-03-22 08:04
@JonForShort, you're welcome! Thank you for reporting the problem, I'd prefer to keep it open since it requires more solid solution from oneTBB side. I'll rename it to provide more precise summary.

**Comment by AlexVeprev** [comment] 2021-03-22 08:09
The similar issue is reproducible with clang++ for Linux:
```
> cmake -G Ninja -DCMAKE_CXX_COMPILER=clang++ ..
> ninja
...
clang: error: argument unused during compilation: '-MMD' [-Werror,-Wunused-command-line-argument]...
```

**Comment by AlexVeprev** [comment] 2021-03-26 07:40
@JonForShort, now it should be fixed in master, could you please check it on your side?

**Comment by JonForShort** [comment] 2021-03-28 03:18
Hi @AlexVeprev , I verified that the fix works on my side.  Thanks again!

**Comment by AlexVeprev** [comment] 2021-03-29 08:57
@JonForShort, thank you for the confirmation!

**Closed by AlexVeprev** 2021-03-29 08:57 UTC
