### ISSUE TITLE
Exception from parallel_for called from parallel_reduce within global task arena causes segfault

### ISSUE THREAD

**Issue by fexolm** [oneapi-src/oneTBB#669] opened 2021-11-24 11:35 UTC
Here is the reproducer:
```cpp
#include <tbb/parallel_for.h>
#include <tbb/parallel_reduce.h>
#include <tbb/task_arena.h>
#include <atomic>
#include <chrono>
#include <future>
#include <iostream>
#include <stdexcept>

std::atomic<bool> cancelation;
tbb::task_arena g_tbb_arena;

void reduce() {
  g_tbb_arena.execute([&] {
    tbb::this_task_arena::isolate([&] {
      tbb::parallel_for(tbb::blocked_range<int>(0, 1000, 1), [](auto r) {
        while (!cancelation)
          ;
        throw std::runtime_error("work was canceled");
      });
    });
  });
}

int main() {
  cancelation = false;

  auto reduce_thread = std::async(std::launch::async, [&]() {
    g_tbb_arena.execute([&] {
      tbb::this_task_arena::isolate([&] {
        tbb::parallel_reduce(
            tbb::blocked_range<int>(0, 1000, 1),
            0,
            [](auto r, int acc) {
              reduce();
              return 5;
            },
            [](int lhs, int rhs) {
              reduce();
              return 5;
            });
      });
    });
  });

  auto cancelation_thread = std::async(std::launch::async, [&]() {
    std::this_thread::sleep_for(std::chrono::seconds(6));
    cancelation = true;
  });

  cancelation_thread.get();
  reduce_thread.get();
}
```

**Comment by anton-malakhov** [comment] 2021-11-24 11:49
This is related to https://github.com/omnisci/omniscidb/pull/673

**Comment by alexey-katranov** [comment] 2021-11-24 12:43
The exception `throw std::runtime_error("work was canceled");` is never called. Try to wrap `  reduce_thread.get();` into `try`/`catch` block, e.g.`
```
try {
    reduce_thread.get();
} catch (...) {
    std::cout << "Exception is caught\n";
}
```

If you want to cancel some parallel algorithm from an external thread consider using explicit [`task_group_context`](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/task_scheduler/scheduling_controls/task_group_context_cls.html) and `task_group_context::cancel_group_execution`

**Comment by fexolm** [comment] 2021-11-24 12:55
@alexey-katranov Thanks for your advice.  I understand, that I don't catch exception here, but It is not really the case. Here I expect that exception would be normally propagated to the main thread as id does, without global task arena. But when I use task arena, that code causes segfault somewhere in the tbb internals.

**Comment by alexey-katranov** [comment] 2021-11-24 13:06
It seems I misunderstand the issue, thank you for the clarification. I'll try to reproduce the issue on big machine and come back.

**Comment by alexey-katranov** [comment] 2021-11-24 13:33
I tried 26 cores (as well as 44) but no segfault in oneTBB internal. Can you please provide more details? What is OS and oneTBB version?

**Comment by fexolm** [comment] 2021-11-24 13:55
I use Ubuntu 20.04 and master branch

Here is output with TBB_VERSION=1
```
oneTBB: SPECIFICATION VERSION 1.0
oneTBB: VERSION 2021.6
oneTBB: INTERFACE VERSION 12060
oneTBB: TBB_USE_DEBUG 0
oneTBB: TBB_USE_ASSERT 0
oneTBB: ALLOCATOR scalable_malloc
oneTBB: TOOLS SUPPORT disabled
TBBmalloc: SPECIFICATION VERSION 1.0
TBBmalloc: VERSION 2021.6
TBBmalloc: INTERFACE VERSION 12060
TBBmalloc: TBB_USE_DEBUG 0
TBBmalloc: TBB_USE_ASSERT 0
TBBmalloc: huge pages not requested
```

**Comment by fexolm** [comment] 2021-11-24 15:01
For some reason, I wasn't able to reproduce the issue in clean environment. It looks like I would need more time to find what caused that errors. I will write you, as soon as I found smth. Thanks for your help.

**Comment by fexolm** [comment] 2021-11-25 09:26
I found out, that the problem only reproduces, when linking reproducer with libunwind. 
I was able to reproduce the issue, by compiling with the following command.
```
g++ -O0 -g reproducer.cpp  -ltbb -lunwind -pthread -o reproducer
```

**Comment by alexey-katranov** [comment] 2021-12-02 06:34
The root cause is incorrect register calculation during unwind in `libunwind`. The issue was fixed in https://github.com/libunwind/libunwind/pull/46. So, consider using `libunwind` with version 1.3.0 or newer. (Note that Ubuntu 20.04 comes with `libunwind` 1.2.1)

Some details:
I reduced the reproducer:
```C++
#include <tbb/task_arena.h>
#include <tbb/task_group.h>
#include <algorithm>

void fill() {
    volatile unsigned int pad[128];
    // fill the stack with something conspicuous
    std::fill(pad, pad + 128, 0xdeadbeef);
}

tbb::task_arena g_tbb_arena;
int main() {
    tbb::task_group tg;
    tg.run_and_wait([] {
        fill();
        g_tbb_arena.execute([] {
            throw 0;
        });
    });
}
```

The backtrace when crashed:
```
#0  0x00007ffff7f9b393 in std::__atomic_base<unsigned long>::load (__m=std::memory_order_acquire, this=0x8) at /usr/include/c++/9/bits/atomic_base.h:413
#1  tbb::detail::d1::wait_context::continue_execution (this=0x0) at /mnt/c/github/oneTBB/src/tbb/../../include/oneapi/tbb/detail/_task.h:119
#2  tbb::detail::r1::external_waiter::continue_execution (this=0x7fffffffe140, t=<synthetic pointer>: 0x0, slot=...) at /mnt/c/github/oneTBB/src/tbb/waiters.h:131
#3  tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::external_waiter> (this=0xdeadbeefdeadbee7, t=0x0, waiter=...)
    at /mnt/c/github/oneTBB/src/tbb/task_dispatcher.h:353
```
Pay attention to `this` pointer on frame 3: it is `0xdeadbeefdeadbeef - 0x8`. I.e. `this` pointer is corrupted with values that we used to fill the stack. The compiler optimizes `this->m_execute_data_ext` into `r12` and uses it as a base address to calculate other fields addresses and `this` value. However, `r12` is callee preserved register, so it is unwinding algorithm responsibility to restore it during an exception.
It should be noted that the reproducer changes `r12` only in `task_arena::execute`, so we either have an error in `.eh_frames` section or `libunwind` logic. The `.eh_frames` seems valid:
```
// task_arena::execute body:
000012dc 000000000000004c 00000f0c FDE cie=000003d4 pc=0000000000010f50..00000000000123e0
  Augmentation data:     a4 63 00 00
  DW_CFA_advance_loc: 9 to 0000000000010f59
  DW_CFA_def_cfa: r10 (r10) ofs 0
  DW_CFA_advance_loc: 9 to 0000000000010f62
  DW_CFA_expression: r6 (rbp) (DW_OP_breg6 (rbp): 0)
  DW_CFA_advance_loc: 7 to 0000000000010f69
  DW_CFA_expression: r15 (r15) (DW_OP_breg6 (rbp): -8)
  DW_CFA_expression: r14 (r14) (DW_OP_breg6 (rbp): -16)
  DW_CFA_advance_loc: 9 to 0000000000010f72
  DW_CFA_def_cfa_expression (DW_OP_breg6 (rbp): -40; DW_OP_deref)
  DW_CFA_expression: r13 (r13) (DW_OP_breg6 (rbp): -24)
  DW_CFA_expression: r12 (r12) (DW_OP_breg6 (rbp): -32)
  DW_CFA_advance_loc: 8 to 0000000000010f7a
  DW_CFA_expression: r3 (rbx) (DW_OP_breg6 (rbp): -48)
  DW_CFA_advance_loc2: 892 to 00000000000112f6
  DW_CFA_remember_state
  DW_CFA_def_cfa: r10 (r10) ofs 0
  DW_CFA_advance_loc: 13 to 0000000000011303
  DW_CFA_def_cfa: r7 (rsp) ofs 8
  DW_CFA_advance_loc: 5 to 0000000000011308
  DW_CFA_restore_state
  DW_CFA_nop
  DW_CFA_nop
  DW_CFA_nop

// task_arena::execute unwinding part:
0000132c 0000000000000034 00000f5c FDE cie=000003d4 pc=000000000000d124..000000000000d25e
  Augmentation data:     9f 63 00 00
  DW_CFA_def_cfa_expression (DW_OP_breg6 (rbp): -40; DW_OP_deref)
  DW_CFA_expression: r3 (rbx) (DW_OP_breg6 (rbp): -48)
  DW_CFA_expression: r6 (rbp) (DW_OP_breg6 (rbp): 0)
  DW_CFA_expression: r12 (r12) (DW_OP_breg6 (rbp): -32)
  DW_CFA_expression: r13 (r13) (DW_OP_breg6 (rbp): -24)
  DW_CFA_expression: r14 (r14) (DW_OP_breg6 (rbp): -16)
  DW_CFA_expression: r15 (r15) (DW_OP_breg6 (rbp): -8)
```
 While the frame seems valid, it is not typical to encode DWARF expressions to calculate stack address from `rbp`. The typical frame looks like (there is no `DW_CFA_expression`):
```
// some other function:
000012b8 0000000000000020 000012bc FDE cie=00000000 pc=0000000000014fe0..000000000001504b
  DW_CFA_advance_loc: 5 to 0000000000014fe5
  DW_CFA_def_cfa_offset: 16
  DW_CFA_offset: r6 (rbp) at cfa-16
  DW_CFA_advance_loc: 16 to 0000000000014ff5
  DW_CFA_def_cfa_offset: 32
  DW_CFA_advance_loc1: 79 to 0000000000015044
  DW_CFA_remember_state
  DW_CFA_def_cfa_offset: 16
  DW_CFA_advance_loc: 1 to 0000000000015045
  DW_CFA_def_cfa_offset: 8
  DW_CFA_advance_loc: 1 to 0000000000015046
  DW_CFA_restore_state
  DW_CFA_nop
```

Therefore, `libunwind` requires some advanced logic to calculate stack addresses and register values. While the mentioned fix states that it fixes a crash, strictly speaking, it is memory corruption because the register calculation logic is based on some previous values of the registers that can give some reasonable addresses on the stack.

**Comment by anton-potapov** [comment] 2021-12-07 07:40
@alexey-katranov can we close this ?

**Comment by fexolm** [comment] 2021-12-14 09:15
Thanks @alexey-katranov!

**Closed** 2021-12-14 14:01 UTC
