### ISSUE TITLE
Re: Errors compiling Intel OneAPI TBB c++ include file concurrent_vector.h 

### ISSUE THREAD

**Issue by cpodczerwinski** [oneapi-src/oneTBB#1428] opened 2024-06-27 00:24 UTC
I'm using C++ in the Visual Studio Community Edition on Windows 11.  I am using the latest builds of the OneAPI and Visual Studio which I reinstalled after finding the problem.

When I use the OneAPI TBB concurrent_vector template in a very small completely isolated application it builds and runs fine. 
When I include the file windows.h above the oneapi/tbb include files. I get the compiler error messages below.  When I include windows,h below the oneapi/tbb include files the small isolated test project builds and runs fine.  I attached the source code for the small test project. 

I need to integrate TBB functions in my production app as soon as I can, Can you suggest a work around until the problem is fixed?   

Here are the error messages I get.  Thank you in advance for your help.  Regards Craig

main.cpp
1>D:\Craig\Visual Studio 2022\Projects\OneAPIParallelFunctionEvaluation\OneAPIParallelFunctionEvaluation\main.cpp(2,9): warning C4005: 'WIN32_LEAN_AND_MEAN': macro redefinition
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(488,21): error C2589: '(': illegal token on right side of '::'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(488,21): error C3878: syntax error: unexpected token '(' following 'expression'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(488,21): message : error recovery skipped: '( ( this  . . . identifier'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(488,21): message : parsing resumes here
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(488,21): error C2760: syntax error: ')' was unexpected here; expected ';'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(488,21): error C3878: syntax error: unexpected token ')' following 'jump_statement'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(488,21): message : error recovery skipped: ') ) <'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(488,21): error C3878: syntax error: unexpected token ')' following 'expression_statement'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(488,21): message : error recovery skipped: ') ?'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(488,21): error C2760: syntax error: ':' was unexpected here; expected ';'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(488,21): error C3878: syntax error: unexpected token ':' following 'expression_statement'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(488,21): message : error recovery skipped: ':'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(488,21): message : error recovery skipped: ')'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(637,25): error C2589: '(': illegal token on right side of '::'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(637,25): error C3878: syntax error: unexpected token '(' following 'expression'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(637,25): message : error recovery skipped: '( ( identifier'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(637,25): error C2760: syntax error: ')' was unexpected here; expected ';'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(637,25): error C3878: syntax error: unexpected token ')' following 'jump_statement'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(637,25): error C3878: syntax error: unexpected token ')' following 'statement'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(637,25): error C3878: syntax error: unexpected token ')' following 'statement_seq'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(637,25): error C2760: syntax error: ')' was unexpected here; expected '}'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(637,25): error C3878: syntax error: unexpected token ')' following 'compound_statement'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(637,25): error C3878: syntax error: unexpected token ')' following 'selection_statement'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(637,25): message : error recovery skipped: ') <'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(637,25): error C3878: syntax error: unexpected token ')' following 'expression_statement'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(637,25): message : error recovery skipped: ') ?'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(637,25): error C2760: syntax error: ':' was unexpected here; expected ';'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(637,25): error C3878: syntax error: unexpected token ':' following 'expression_statement'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(637,25): message : error recovery skipped: ':'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(637,25): message : error recovery skipped: ')'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(924,52): error C2589: '(': illegal token on right side of '::'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(924,52): error C2760: syntax error: ')' was unexpected here; expected ';'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(924,52): error C3878: syntax error: unexpected token ')' following 'expression_statement'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(924,52): error C3878: syntax error: unexpected token ')' following 'statement'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(924,52): error C3878: syntax error: unexpected token ')' following 'statement_seq'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(924,52): error C2760: syntax error: ')' was unexpected here; expected '}'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(924,52): error C3878: syntax error: unexpected token ')' following 'compound_statement'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(924,52): error C3878: syntax error: unexpected token ')' following 'selection_statement'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(924,52): message : error recovery skipped: ')'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(926,43): error C2065: 'last_index_to_destroy': undeclared identifier
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(968,40): error C2589: '(': illegal token on right side of '::'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(968,40): error C2760: syntax error: ')' was unexpected here; expected ';'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(968,40): error C3878: syntax error: unexpected token ')' following 'expression_statement'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(968,40): error C3878: syntax error: unexpected token ')' following 'statement'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(968,40): error C3878: syntax error: unexpected token ')' following 'statement_seq'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(968,40): error C2760: syntax error: ')' was unexpected here; expected '}'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(968,40): error C3878: syntax error: unexpected token ')' following 'compound_statement'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(968,40): error C3878: syntax error: unexpected token ')' following 'selection_statement'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(968,40): message : error recovery skipped: ')'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(970,102): error C2065: 'max_block': undeclared identifier
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(972,51): error C2065: 'max_block': undeclared identifier
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(981,37): error C2589: '(': illegal token on right side of '::'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(981,37): error C3878: syntax error: unexpected token '(' following 'expression'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(981,37): message : error recovery skipped: '( ( this  . . . identifier'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(981,37): error C2760: syntax error: ')' was unexpected here; expected ';'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(981,37): error C2760: syntax error: ')' was unexpected here; expected 'statement'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(981,37): message : error recovery skipped: ') <'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(981,37): error C3878: syntax error: unexpected token ')' following 'expression_statement'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(981,37): message : error recovery skipped: ') ?'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(981,37): error C2065: 'max_block': undeclared identifier
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(981,37): error C2760: syntax error: ':' was unexpected here; expected ';'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(981,37): error C3878: syntax error: unexpected token ':' following 'expression_statement'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(981,37): message : error recovery skipped: ':'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(981,37): message : error recovery skipped: ')'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(981,91): error C2760: syntax error: ')' was unexpected here; expected ';'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(981,91): error C3878: syntax error: unexpected token ')' following 'expression_statement'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(981,91): message : error recovery skipped: ')'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(987,15): error C2760: syntax error: ')' was unexpected here; expected ';'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(987,15): error C3878: syntax error: unexpected token ')' following 'expression_statement'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(987,15): message : error recovery skipped: ') .'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(994,82): error C2065: 'max_block': undeclared identifier
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(996,55): error C2065: 'max_block': undeclared identifier
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(1002,35): error C2065: 'max_block': undeclared identifier
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(1011,38): error C2065: 'max_block': undeclared identifier
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(1021,51): error C2065: 'max_block': undeclared identifier
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.12\include\oneapi\tbb\concurrent_vector.h(1025,98): error C2065: 'max_block': undeclared identifier
1>D:\Craig\Visual Studio 2022\Projects\OneAPIParallelFunctionEvaluation\OneAPIParallelFunctionEvaluation\main.cpp(100,43): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data

**Comment by cpodczerwinski** [comment] 2024-06-27 00:31
See the attached file for the source code needed to reproduce the problem.

**Comment by omalyshe** [comment] 2024-06-27 08:18
> See the attached file for the source code needed to reproduce the problem.

Looks like the attachment is missed.

**Comment by dnmokhov** [comment] 2024-06-28 00:52
Thank you for reporting this, @cpodczerwinski. Have you tried defining `NOMINMAX` before including windows.h?

The problem is in the definition of the `min` and `max` macros in the Windows Platform SDK headers, which can be disabled with `NOMINMAX`. You can read [here](https://learn.microsoft.com/en-us/archive/msdn-magazine/2016/september/c-unicode-encoding-conversions-with-stl-strings-and-win32-apis) (search in page for "prevent the definition of the min and max Windows-specific preprocessor macros") for more details.

Closing this as a duplicate of #1407.

**Comment by cpodczerwinski** [comment] 2024-06-28 00:55
Thank you. I’ll try it tomorrow morning. Regards Craig.

Sent from AT&T Yahoo Mail for iPhone


On Thursday, June 27, 2024, 7:52 PM, Dmitri Mokhov ***@***.***> wrote:




Thank you for reporting this, @cpodczerwinski. Have you tried defining NOMINMAX before including windows.h?

The problem is in the definition of the min and max macros in the Windows Platform SDK headers, which can be disabled with NOMINMAX. You can read here (search in page for "prevent the definition of the min and max Windows-specific preprocessor macros") for more details.

Closing this as a duplicate of #1407.

**Comment by cpodczerwinski** [comment] 2024-06-28 14:39
I tried defining NOMINMAX. That did not fix the problem.
Please let me know what else I can try
RegardsCraig
    On Thursday, June 27, 2024 at 07:55:29 PM CDT, Craig Podczerwinski ***@***.***> wrote:  
 
 
Thank you. I’ll try it tomorrow morning. Regards Craig.

Sent from AT&T Yahoo Mail for iPhone


On Thursday, June 27, 2024, 7:52 PM, Dmitri Mokhov ***@***.***> wrote:




Thank you for reporting this, @cpodczerwinski. Have you tried defining NOMINMAX before including windows.h?

The problem is in the definition of the min and max macros in the Windows Platform SDK headers, which can be disabled with NOMINMAX. You can read here (search in page for "prevent the definition of the min and max Windows-specific preprocessor macros") for more details.

Closing this as a duplicate of #1407.

**Comment by cpodczerwinski** [comment] 2024-06-28 14:48
I tried defining NOMINMAX before including windows.h that did not fix the problem. Here are the error messages I'm getting.

1>D:\Craig\Visual Studio 2022\Projects\CraigsSystem\src\portfolioreturnobjectivefunction.cpp(6,9): warning C4603: 'NOMINMAX': macro is not defined or definition is different after precompiled header use
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.13\include\oneapi\tbb\concurrent_vector.h(637,25): error C2589: '(': illegal token on right side of '::'
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.13\include\oneapi\tbb\concurrent_vector.h(637,20): error C2062: type 'unknown-type' unexpected
1>C:\Program Files (x86)\Intel\oneAPI\tbb\2021.13\include\oneapi\tbb\concurrent_vector.h(637,25): error C2059: syntax error: ')'

Can you suggest another approach.

Regards
Craig

**Comment by dnmokhov** [comment] 2024-06-28 14:51
@cpodczerwinski, can you please attach the source code needed to reproduce the problem?

**Comment by NeedsMoar** [comment] 2024-07-02 16:46
> I tried defining NOMINMAX before including windows.h that did not fix the problem. Here are the error messages I'm getting.
> 
> 1>D:\Craig\Visual Studio 2022\Projects\CraigsSystem\src\portfolioreturnobjectivefunction.cpp(6,9): warning C4603: 'NOMINMAX': macro is not defined or definition is different after precompiled header use 

The warning more or less tells you the problem.  You've got precompiled headers enabled;  NOMINMAX probably isn't defined in the pch.h file, now you've gone and defined it but the precompiled header is undefing it (and is almost certainly being processed first, and is probably included from main.cpp)  Try a clean / build or rebuild (which you should do when changing preprocessor macros anyway) and it should start working.

and I'd probably read this for future reference:

https://learn.microsoft.com/en-us/cpp/build/creating-precompiled-header-files?view=msvc-170

**Comment by cpodczerwinski** [comment] 2024-07-08 20:44
Good morning:
I resolved the problem problem by taking the following actions.
I included tbb.h in my precompiled header file for my application above windows.h
I replaced all of the old style calls to min() and max() with std::min() and std::max() calls.
The application builds and runs with no issues.
Thank you for your help.RegardsCraig
    On Tuesday, July 2, 2024 at 11:47:01 AM CDT, NeedsMoar ***@***.***> wrote:  
 
 



I tried defining NOMINMAX before including windows.h that did not fix the problem. Here are the error messages I'm getting.

1>D:\Craig\Visual Studio 2022\Projects\CraigsSystem\src\portfolioreturnobjectivefunction.cpp(6,9): warning C4603: 'NOMINMAX': macro is not defined or definition is different after precompiled header use


The warning more or less tells you the problem. You've got precompiled headers enabled; NOMINMAX probably isn't defined in the pch.h file, now you've gone and defined it but the precompiled header is undefing it (and is almost certainly being processed first, and is probably included from main.cpp) Try a clean / build or rebuild (which you should do when changing preprocessor macros anyway) and it should start working.

and I'd probably read this for future reference:

https://learn.microsoft.com/en-us/cpp/build/creating-precompiled-header-files?view=msvc-170

**Closed** 2024-07-09 22:38 UTC
Labels: bug
