### ISSUE TITLE
WASM - linking to both `-ltbb` and `-ltbbmalloc` gives duplicate symbol error for `itt_notify`

### ISSUE THREAD

**Issue by andrjohns** [oneapi-src/oneTBB#1392] opened 2024-06-02 17:54 UTC
After building and installing `oneTBB` with the configuration:
```
  emcmake cmake \
	    -DCMAKE_BUILD_TYPE=Release \
	    -DCMAKE_FIND_ROOT_PATH=$(WASM) \
	    -DCMAKE_INSTALL_PREFIX:PATH=$(WASM) \
	    -DTBB_STRICT=OFF \
	    -DCMAKE_CXX_FLAGS=-Wno-unused-command-line-argument \
	    -DTBB_DISABLE_HWLOC_AUTOMATIC_SEARCH=ON \
	    -DBUILD_SHARED_LIBS=OFF \
	    -DTBB_EXAMPLES=OFF \
	    -DTBB_TEST=OFF \
	    -DEMSCRIPTEN_WITHOUT_PTHREAD=true \
	    .. && \
	  cmake --build . && \
	  cmake --install .
```

Subsequent compilation that attempts to link against the `libtbb.a` and `libtbbmalloc.a` files gives errors for duplicate symbols:
```
em++ -std=gnu++17 -DNDEBUG -I../inst/include -I/Users/georgestagg/work/webr/wasm/include   -I/Users/georgestagg/work/webr/wasm/include -I/Users/georgestagg/work/webr/R/build/R-4.4.0/build/include -I/Users/georgestagg/work/webr/R/build/R-4.4.0/src/include -s USE_BZIP2=1 -s USE_ZLIB=1 -std=gnu++11 -fPIC    -Oz -fPIC -fwasm-exceptions -s SUPPORT_LONGJMP=wasm -DRCPP_DEMANGLER_ENABLED=0 -D__STRICT_ANSI__  -c init.cpp -o init.o
em++ -std=gnu++17 -DNDEBUG -I../inst/include -I/Users/georgestagg/work/webr/wasm/include   -I/Users/georgestagg/work/webr/wasm/include -I/Users/georgestagg/work/webr/R/build/R-4.4.0/build/include -I/Users/georgestagg/work/webr/R/build/R-4.4.0/src/include -s USE_BZIP2=1 -s USE_ZLIB=1 -std=gnu++11 -fPIC    -Oz -fPIC -fwasm-exceptions -s SUPPORT_LONGJMP=wasm -DRCPP_DEMANGLER_ENABLED=0 -D__STRICT_ANSI__  -c options.cpp -o options.o
em++ -std=gnu++17 -s SIDE_MODULE=1 -s WASM_BIGINT -s ASSERTIONS=1 -L/Users/georgestagg/work/webr/wasm/lib -L/Users/georgestagg/work/webr/wasm/R-4.4.0/lib/R/lib -s USE_BZIP2=1 -s USE_ZLIB=1 -fwasm-exceptions -s SUPPORT_LONGJMP=wasm -Oz -o RcppParallel.so init.o options.o -Wl,-L,/Users/georgestagg/work/webr/wasm/lib -Wl,-rpath,/Users/georgestagg/work/webr/wasm/lib -ltbb -ltbbmalloc
em++: warning: ignoring unsupported linker flag: `-rpath` [-Wlinkflags]
wasm-ld: error: duplicate symbol: __itt__ittapi_global
>>> defined in /Users/georgestagg/work/webr/wasm/lib/libtbb.a(itt_notify.cpp.o)
>>> defined in /Users/georgestagg/work/webr/wasm/lib/libtbbmalloc.a(itt_notify.cpp.o)

wasm-ld: error: duplicate symbol: __itt_detach_ptr__3_0
>>> defined in /Users/georgestagg/work/webr/wasm/lib/libtbb.a(itt_notify.cpp.o)
>>> defined in /Users/georgestagg/work/webr/wasm/lib/libtbbmalloc.a(itt_notify.cpp.o)

wasm-ld: error: duplicate symbol: __itt_sync_create_ptr__3_0
>>> defined in /Users/georgestagg/work/webr/wasm/lib/libtbb.a(itt_notify.cpp.o)
>>> defined in /Users/georgestagg/work/webr/wasm/lib/libtbbmalloc.a(itt_notify.cpp.o)

wasm-ld: error: duplicate symbol: __itt_sync_rename_ptr__3_0
>>> defined in /Users/georgestagg/work/webr/wasm/lib/libtbb.a(itt_notify.cpp.o)
>>> defined in /Users/georgestagg/work/webr/wasm/lib/libtbbmalloc.a(itt_notify.cpp.o)

wasm-ld: error: duplicate symbol: __itt_sync_destroy_ptr__3_0
>>> defined in /Users/georgestagg/work/webr/wasm/lib/libtbb.a(itt_notify.cpp.o)
>>> defined in /Users/georgestagg/work/webr/wasm/lib/libtbbmalloc.a(itt_notify.cpp.o)
...
```

I can see that the `itt_notify.cpp` file is included in the `CMakeLists` for both [`tbbmalloc`](https://github.com/oneapi-src/oneTBB/blob/d8c53ce141bada427a6eb56fc2fd43d7a210980e/src/tbbmalloc/CMakeLists.txt#L21) and [`tbb`](https://github.com/oneapi-src/oneTBB/blob/d8c53ce141bada427a6eb56fc2fd43d7a210980e/src/tbb/CMakeLists.txt#L25), should this be excluded from one of them when building for WASM?

**Comment by andrjohns** [comment] 2024-06-03 04:15
I've since worked around this by adding `-DTBB_COMMON_COMPILE_FLAGS="-U__TBB_USE_ITT_NOTIFY"` to the cmake flags

**Comment by JhaShweta1** [comment] 2024-06-09 19:36
Hi, Thank you for reporting this. I tried with a simple example and couldn't reproduce the error. I will try to replicate this some more and see what we can do about this duplicated linking. Glad that you have a work-around until we resolve this.

**Comment by JhaShweta1** [comment] 2024-06-11 16:09
Hi, I was wondering if you really need to link both tbb and tbbmalloc? Also, oneTBB doesn't support static tbbmalloc. May be you can instead use allocator provided by emscripten - mimalloc.

**Comment by JhaShweta1** [comment] 2024-06-25 18:41
Hi, Since no updates have been received, I am closing this issue for now. Please reopen it if the matter remains unresolved.

**Closed by JhaShweta1** 2024-06-25 18:41 UTC
Labels: question
