### ISSUE TITLE
Incomplete compatibility layer (cond var)

### ISSUE THREAD

**Issue by anton-malakhov** [oneapi-src/oneTBB#36] opened 2017-09-22 22:18 UTC
I used `tbb/compat/condition_variable` in order to make source code backward-compatible with old compilers.
However, I had to write the following instead of just including single compat file:
```
#include <tbb/tbb.h>
#include <tbb/compat/condition_variable>
#if TBB_IMPLEMENT_CPP0X
namespace std { using tbb::mutex; }
#define unique_ptr auto_ptr
#else
#include <condition_variable>
#include <mutex>
#include <memory>
#endif
```
So, at least, current implementation misses `namespace std { using tbb::mutex; }` part. Ideally, I want to complete story by  being forward compatible automatically. I.e. when the backward-compatible code is being compiled by new compiler, it should just switch to all the standard implementations without additional effort.

**Comment by aleksei-fedotov** [comment] 2020-04-01 08:59
Given the existence of the workaround the priority of the issue is low. Moreover, according to [this forum topic](https://software.intel.com/en-us/forums/intel-threading-building-blocks/topic/815880) there won't be a compatibility layer for condition variable anymore. So, I propose closing this issue. Interested people could always reopen it if they think there is something to discuss further.

**Closed by aleksei-fedotov** 2020-04-01 08:59 UTC
