### ISSUE TITLE
Is this bug in reduction?

### ISSUE THREAD

**Issue by shersoni610** [oneapi-src/oneTBB#226] opened 2020-03-14 03:36 UTC
Hello, 

I wrote a simple code to understand the parallel_reduce function:
class SumVec
{
    float* data;
public:
    float valsum;
    void operator()( const blocked_range<size_t>& r )
    {
        float *a    = data;
        float lsum  = valsum;
        for( size_t i=r.begin(); i!=r.end(); ++i )
            lsum += data[i];
        valsum = lsum;
    }

    SumVec( SumVec& x, split ) : data(x.data), valsum(0) {}

    void join( const SumVec& y )
    {
        valsum+=y.valsum;
    }

    SumVec(float *a) : data(a), valsum(0)
    {}
};

int main()
{
    int N = 99999;
    vector<float> a(N);

    float sum = 0.0;
    for( int i = 0; i < N; i++) {
        a[i] = drand48();
        sum += a[i];
    }
    printf( "%f \n", sum);

    SumVec sf(&a[0]);
    parallel_reduce( blocked_range<size_t>(0,N), sf );
    printf( "%f \n", sf.valsum);
    return 0;
}

And I got wrong result as:
49950.429688 
49950.453125 

What is the mistake I have made in the code? Can someone clarify?

Thanks

**Comment by goryachih** [comment] 2020-03-16 09:52
Hi,
Different results are caused by non-associativity of float operations (due to rounding).  `parallel_reduce` may perform operations in different order compare to serial reduction and even to another `parallel_reduce`  run.  If you want a reproducible parallel reduction consider `parallel_deterministic_reduce`, but its result still may differ from serial reduction for non-assiciative operations.
For details see [https://www.threadingbuildingblocks.org/docs/help/tbb_userguide/Design_Patterns/Reduction.html](url)

**Comment by alexey-katranov** [comment] 2020-03-16 10:21
You might want to consider [the article](https://software.intel.com/en-us/blogs/2012/05/11/deterministic-reduction-a-new-community-preview-feature-in-intel-threading-building-blocks) about deterministic reduction in TBB.

**Comment by shersoni610** [comment] 2020-03-17 07:09
But it seems the error is beyond acceptable range. I was expecting that accumulated error to be within 5 to 6 decimals.

**Comment by goryachih** [comment] 2020-03-19 16:18
As example, you can calculate the serial sum in reverse order and error will occur. But with double it will eliminated.

**Comment by aleksei-fedotov** [comment] 2020-04-08 08:22
Closing the issue as addressed. Please reopen it if you think something is not clear and more info is required.

**Closed by aleksei-fedotov** 2020-04-08 08:22 UTC
