### ISSUE TITLE
libtbb_preview.so.2 not found by the tbb CMake

### ISSUE THREAD

**Issue by tsung-wei-huang** [oneapi-src/oneTBB#282] opened 2020-09-23 19:36 UTC
I follow the instruction [here](https://github.com/oneapi-src/oneTBB/tree/tbb_2020/cmake#about-tbb) to use TBB in my project as follows:

```
# tbb package
# set TBB_ROOT to the home of tbb

include(${TBB_ROOT}/cmake/TBBBuild.cmake)
tbb_build(TBB_ROOT ${TBB_ROOT} CONFIG_DIR TBB_DIR MAKE_ARGS tbb_cpf=1)
find_package(TBB REQUIRED tbb_preview)

add_executable(
  wavefront
  main.cpp  # with tbb-specific code
)
target_link_libraries(
  wavefront
  ${TBB_IMPORTED_TARGETS}
)
```

when I run wavefront, I kept getting this error `./wavefront: error while loading shared libraries: libtbb_preview.so.2: cannot open shared object file: No such file or directory`. How can I fit it? I have included tbb to a 3rd-party folder in my project.

**Comment by AlexVeprev** [comment] 2020-09-24 09:42
Hi @tsung-wei-huang, do you relocate libtbb_preview.so.2 after the build?
Could you please provide build log collected with VERBOSE enabled: `make VERBOSE=1`?
I'm mostly interested in `-Wl,-rpath,` key used during the "Linking CXX" stage. It should be `-Wl,-rpath,<path-to-tbb-libraries>` and if `<path-to-tbb-libraries>` folder exists and contains libtbb_preview.so.2 everything should be ok with running.

BTW, which OS and compiler do you use?
I tried your example on Ubuntu 18.04 with g++ 7.4.0 and didn't reproduce the error. Running is ok, `ldd wavefront` shows that `libtbb_preview.so.2` is found in the expected place.

**Comment by tsung-wei-huang** [comment] 2020-09-24 18:04
@AlexVeprev thanks for your reply. Indeed, I imported TBB in my [taskflow](https://github.com/taskflow/taskflow) project using out-of-tree build: 

```bash
~$ git clone https://github.com/taskflow/taskflow.git
~$ cd taskflow/ 
~$ mkdir build
~$ cd build
~$ cmake ../ -DTF_BUILD_BENCHMARKS=ON
~$ make
...
CMake Warning (dev) at benchmarks/CMakeLists.txt:29 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable TBB_ROOT is set to:

    /home/tsung-wei/Code/taskflow/3rd-party/tbb

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
....
```

You can see the [top-level cmake](https://github.com/taskflow/taskflow/blob/713b72c08b99566acb8c613179049bf0dd7a8c53/CMakeLists.txt#L263) where we include the [taskflow/benchmarks/CMakeLists.txt](https://github.com/taskflow/taskflow/blob/master/benchmarks/CMakeLists.txt) to compile all examples linking TBB. The compilation successfully completes but when I run `taskflow/benchmarks/wavefront` it always complains not finding the shared library. I am on the same ubuntu as you with a different gcc-8-3, but I don't think that matters. 

Please help! Thanks

**Comment by AlexVeprev** [comment] 2020-09-24 21:40
@tsung-wei-huang unfortunately I haven't managed to reproduce the issue even with the newest CMake. But I have an assumption that the problem is in `TBB_ROOT` name and update of [CMP0074](https://cmake.org/cmake/help/v3.18/policy/CMP0074.html) policy:
> CMake version 3.18.3 warns when the policy is not set and uses OLD behavior. 

Which CMake version do you use?

I see you already tried something with CMP0074 in [benchmarks/CMakeLists.txt#L27](https://github.com/taskflow/taskflow/blob/master/benchmarks/CMakeLists.txt#L27), but actually this policy should be set while the `TBB_ROOT` variable is in use. You should either set this policy before initialization of `TBB_ROOT` or (if you need push/pop) consider the following:

```diff
diff --git a/benchmarks/CMakeLists.txt b/benchmarks/CMakeLists.txt
index 354370ca..c3f14898 100644
--- a/benchmarks/CMakeLists.txt
+++ b/benchmarks/CMakeLists.txt
@@ -14,7 +14,8 @@ endif()
 message(STATUS "OpenMP_VERSION: ${OpenMP_VERSION}")
 message(STATUS "OpenMP_CXX_FLAGS: ${OpenMP_CXX_FLAGS}")
 message(STATUS "OpenMP_CXX_LIBRARIES: ${OpenMP_CXX_LIBRARIES}")
-
+cmake_policy(PUSH)
+cmake_policy(SET CMP0074 NEW)
 # tbb package
 if(NOT DEFINED TBB_ROOT)
   set(TBB_ROOT ${TF_3RD_PARTY_DIR}/tbb)
@@ -22,6 +23,8 @@ endif()

 include(${TBB_ROOT}/cmake/TBBBuild.cmake)
 tbb_build(TBB_ROOT ${TBB_ROOT} CONFIG_DIR TBB_DIR MAKE_ARGS tbb_cpf=1)
+unset(TBB_ROOT)  # unset is needed to pop CMP0074 without warning
+cmake_policy(POP)
 #tbb_build(TBB_ROOT ${TBB_ROOT} CONFIG_DIR TBB_DIR)
 #cmake_policy(PUSH)
 #cmake_policy(SET CMP0074 NEW)
```

Also consider renaming `TBB_ROOT` to avoid the policy warning:
```diff
diff --git a/benchmarks/CMakeLists.txt b/benchmarks/CMakeLists.txt
index 354370ca..20f71fb3 100644
--- a/benchmarks/CMakeLists.txt
+++ b/benchmarks/CMakeLists.txt
@@ -16,12 +16,12 @@ message(STATUS "OpenMP_CXX_FLAGS: ${OpenMP_CXX_FLAGS}")
 message(STATUS "OpenMP_CXX_LIBRARIES: ${OpenMP_CXX_LIBRARIES}")

 # tbb package
-if(NOT DEFINED TBB_ROOT)
-  set(TBB_ROOT ${TF_3RD_PARTY_DIR}/tbb)
+if(NOT DEFINED TBB_ROOT_DIR)
+  set(TBB_ROOT_DIR ${TF_3RD_PARTY_DIR}/tbb)
 endif()

-include(${TBB_ROOT}/cmake/TBBBuild.cmake)
-tbb_build(TBB_ROOT ${TBB_ROOT} CONFIG_DIR TBB_DIR MAKE_ARGS tbb_cpf=1)
+include(${TBB_ROOT_DIR}/cmake/TBBBuild.cmake)
+# Note: the first TBB_ROOT is parameter name and shouldn't be renamed
+tbb_build(TBB_ROOT ${TBB_ROOT_DIR} CONFIG_DIR TBB_DIR MAKE_ARGS tbb_cpf=1)
 #tbb_build(TBB_ROOT ${TBB_ROOT} CONFIG_DIR TBB_DIR)
 #cmake_policy(PUSH)
 #cmake_policy(SET CMP0074 NEW)
```

If my proposals don't help or they are not suitable, let's continue troubleshooting.

BTW, you can take a look at [onetbb_2021 branch](https://github.com/oneapi-src/oneTBB/tree/onetbb_2021): it contains oneTBB sources with native CMake support, currently it is in Beta phase, but may be interesting for you.

**Comment by tsung-wei-huang** [comment] 2020-09-25 16:36
@AlexVeprev Thx. Unfortunately, it still doesn't work - quite frustrated. I am switching to your 2021 branch but I have another problem. I want to compile the source of tbb and use it in my project. The page from your link doesn't contain information on how to do this but only integration with the binary package. Could you please help with the cmake I need to write in order to get it to work? Assuming I have the oneTBB source under the folder `${TF_3RD_PARTY_DIR}`

```
add_subdirectory(${TF_3RD_PARTY_DIR}/tbb)  # how can I build the source of tbb in my project and link it to my app?

set(CMAKE_MODULE_PATH "${TF_3RD_PARTY_DIR}/tbb/cmake/;${CMAKE_MODULE_PATH}")

find_package(TBB)

## wavefront computing
add_executable(
  wavefront
  main.cpp  # with tbb-specific code
)
target_link_libraries(
  wavefront
  TBB::tbb
)
```

**Comment by AlexVeprev** [comment] 2020-09-28 08:08
@tsung-wei-huang speaking about oneTBB branch: recently oneTBB sources were published to [master](https://github.com/oneapi-src/oneTBB/tree/master) branch they are a bit newer than current onetbb_2021 branch and include some CMake fixes, so I'd suggest to experiment with oneTBB from master branch.

How to basically use it:
```cmake
option(TBB_TEST OFF)  # skip compilation of TBB tests
add_subdirectory(${TF_3RD_PARTY_DIR}/tbb tbb)  # the second parameter "tbb" is required if ${TF_3RD_PARTY_DIR}/tbb is not subdirectory of current CMakeLists location

## wavefront computing
add_executable(
  wavefront
  main.cpp  # with tbb-specific code
)

target_link_libraries(
  wavefront
  TBB::tbb  # knowing this dependency CMake will compile ${TF_3RD_PARTY_DIR}/tbb from sources
)
```

Note: oneTBB has many changes in comparison with TBB 2020, so you'll have to adopt your source code to work with new TBB.
[Here](https://software.intel.com/content/www/us/en/develop/articles/tbb-revamp.html) you can find some high-level description of the changes.

In order to investigate your initial problem it would be really useful if you can provide Dockerfile or the following info:

- CMake version
- Configuration log
- Build log (make VERBOSE=1)
- ldd output on wavefront binary

**Comment by tsung-wei-huang** [comment] 2020-10-11 18:15
@AlexVeprev thank you very much for the help. I finally got it resolved. Thanks.

**Comment by AlexVeprev** [comment] 2020-10-12 10:53
@tsung-wei-huang, great! Do you have any additional questions in scope of this issue? If no, please close it.

**Comment by tsung-wei-huang** [comment] 2020-10-12 15:23
thanks.

**Closed** 2020-10-12 15:23 UTC
