### ISSUE TITLE
CMake: make TBB_STRICT=OFF disabling global "warning as error"

### ISSUE THREAD

**Issue by AlexVeprev** [oneapi-src/oneTBB#272] opened 2020-08-31 13:46 UTC
Based on comments from #207 by @arihannu.

**Use case**: `TBB_STRICT=OFF` but upper level project globally sets "warning as error" and it leads to failures in TBB compilation (see #207 for details).

The warnings should be considered to be resolved in source code (@alexey-katranov), but also there is a feature request to make `TBB_STRICT` working for the use case above, i.e. to make it disabling global "warning as error".

**Comment by AlexVeprev** [comment] 2020-11-18 09:49
Hi @arihannu, could you please check oneTBB version from master? The latest commit contains updated handling of `TBB_STRICT`: if `TBB_STRICT` is off then `-Werror` or `/WX` are removed from global compile options (set through `CMAKE_CXX_FLAGS` and `add_compile_options()`), some cases may be still uncovered, but seems it should work for your case.

**Comment by arihannu** [comment] 2020-11-27 14:58
Hi @AlexVeprev ,

I am still getting this warning, which happens when I build my library which is using the TBB header:
oneTBB\include\oneapi\tbb\detail/_task.h(233,1): warning C4324: 'tbb::detail::d1::task': structure was padded due to alignment specifier

Would it be possible for you to fix this so that it would not give the warning?

**Comment by AlexVeprev** [comment] 2020-12-01 16:24
@arihannu initially you've reported the problem with the warning treated as error, is it still actual with the updated behavior of `TBB_STRICT=OFF`?

Regarding the warning itself, @alexey-katranov, could you please take a look?

**Comment by arihannu** [comment] 2020-12-02 13:41
@AlexVeprev Yes I am building TBB with TBB_STRICT=OFF, which works fine, however when I build my own library which uses TBB, I get the warning mentioned, which then causes build failure since my lib is built with treat warnings as errors...

**Comment by AlexVeprev** [comment] 2020-12-02 16:24
Hmm, actually currently oneTBB CMake in master can remove some globally set `/WX` and `-Werror` flags if TBB_STRICT is OFF. I'd like to investigate why it doesn't work for you, is your project public? If no, could you please explain how you set "warning as error" and include oneTBB to reproduce the error?

**Comment by JackBoosY** [comment] 2021-03-03 06:26
Any progress guys?

**Comment by AlexVeprev** [comment] 2021-03-03 16:19
@JackBoosY, have you tried setting TBB_STRICT=OFF before TBB integration?

**Comment by JackBoosY** [comment] 2021-03-04 05:49
@AlexVeprev Yes, `-DTBB_STRICT=OFF` was set.

**Comment by anton-potapov** [comment] 2021-12-20 07:31
@AlexVeprev is it still the problem ?

**Comment by AlexVeprev** [comment] 2021-12-20 14:01
Seems `TBB_STRICT=OFF` doesn't work 100% reliably for externally defined "warning as error". Fixing the warning in source code is better way in long term, I believe. Perhaps you @anton-potapov can take a look at it and fix (see the warning above).

**Comment by anton-potapov** [comment] 2021-12-20 17:35
@JackBoosY could you please specify which environment , and compile switches you use?

**Comment by JackBoosY** [comment] 2021-12-22 15:27
@anton-potapov Sorry for late reply.
I'm using Windows 10 with Visual Studio 2017.
The options are:
```cmake
        -DTBB_TEST=OFF
        -DTBB_EXAMPLES=OFF
        -DTBB_STRICT=OFF
        -DTBB_WINDOWS_DRIVER=OFF
        -DTBB_NO_APPCONTAINER=OFF
        -DTBB4PY_BUILD=OFF
        -DTBB_CPF=OFF
        -DTBB_FIND_PACKAGE=OFF
```

**Comment by isaevil** [comment] 2022-11-16 12:42
@JackBoosY sorry for late reply. Is this still a problem for latest oneTBB? Can you please try?

**Comment by Cheney-W** [comment] 2022-11-17 10:23
I can't reproduce this issue.
`-DTBB_STRICT=OFF` is now the default option for `tbb` installation, and `tbb` could install successfully.

**Comment by isaevil** [comment] 2022-11-17 12:14
@Cheney-W @JackBoosY if issue is resolved may I ask you to close this issue?

**Comment by Cheney-W** [comment] 2022-11-18 02:32
I think the issue author should be consulted.

**Comment by JackBoosY** [comment] 2022-11-18 02:33
I'm not the author so I can't close this issue.

**Closed** 2022-11-18 09:23 UTC
Labels: enhancement
