### ISSUE TITLE
Generating random numbers in parallel

### ISSUE THREAD

**Issue by mabalenk** [oneapi-src/oneTBB#1302] opened 2024-01-26 11:53 UTC
Dear all,

I'm learning oneTBB. I need help please. I created a basic vector scaling and addition example (daxpy). Now I would like to use TBB for initialising vectors with random numbers. I wrote a function with TBB's `parallel_for`, but I'm unable to compile the code. Please see my minimal example below:
```
#include <cmath>
#include <cstdio>
#include <random>

#include "oneapi/tbb.h"

using namespace oneapi::tbb;


// Initialises vector with random numbers in parallel
int gen_rand_vec_tbb(int n, double *dx) {

    std::random_device rnd_dev;
    std::mt19937 gen( rnd_dev() );
    std::uniform_real_distribution<> distr(0.0, 1.0);

    parallel_for(blocked_range<size_t>(0, n),
        [=](const blocked_range<size_t> & r) {
            for (size_t i = r.begin(); i < r.end(); i++) {
                dx[i] = distr(gen);
            }
        }
    );

    return 0;
}

// Tests 'daxpy' routine execution
int main(int argc, char *argv[]) {

    int    const N    = 10;
    double const DA   = M_PI;
    int    const INCX = 1;
    int    const INCY = 1;

    double *dx = new double[N]();
    double *dy = new double[N]();

    printf("Scaling factor 'alpha': %f\n\n", DA);

    gen_rand_vec_tbb(N, dx);

    delete[] dx;
    delete[] dy;

    return 0;
}
```
This is the error I receive:
```
g++ -std=c++11 daxpy_mini.cpp -o daxpy_mini -ltbb
daxpy_mini.cpp: In lambda function:
daxpy_mini.cpp:20:30: error: no match for call to '(const std::uniform_real_distribution<>) (const std::mt19937&)'
   20 |                 dx[i] = distr(gen);
      |                         ~~~~~^~~~~
In file included from /usr/include/c++/13.2.1/random:51,
                 from daxpy_mini.cpp:3:
/usr/include/c++/13.2.1/bits/random.h:1904:9: note: candidate: 'template<class _UniformRandomNumberGenerator> std::uniform_real_distribution<_RealType>::result_type std::uniform_real_distribution<_RealType>::operator()(_UniformRandomNumberGenerator&, const param_type&) [with _RealType = double]'
 1904 |         operator()(_UniformRandomNumberGenerator& __urng,
      |         ^~~~~~~~
/usr/include/c++/13.2.1/bits/random.h:1904:9: note:   template argument deduction/substitution failed:
daxpy_mini.cpp:20:30: note:   candidate expects 2 arguments, 1 provided
   20 |                 dx[i] = distr(gen);
      |                         ~~~~~^~~~~
/usr/include/c++/13.2.1/bits/random.h:1899:9: note: candidate: 'std::uniform_real_distribution<_RealType>::result_type std::uniform_real_distribution<_RealType>::operator()(_UniformRandomNumberGenerator&) [with _UniformRandomNumberGenerator = const std::mersenne_twister_engine<long unsigned int, 32, 624, 397, 31, 2567483615, 11, 4294967295, 7, 2636928640, 15, 4022730752, 18, 1812433253>; _RealType = double; result_type = double]' (near match)
 1899 |         operator()(_UniformRandomNumberGenerator& __urng)
      |         ^~~~~~~~
/usr/include/c++/13.2.1/bits/random.h:1899:9: note:   passing 'const std::uniform_real_distribution<>*' as 'this' argument discards qualifiers
```
If I understand correctly, I need to pass `distr` and `gen` to the body of the lambda function. But how do I do that? Thank you for your help!

For a reference, my `daxpy` function is as follows:
```
// Scales and adds two vectors in parallel
int daxpy_tbb(int n, double da, double *dx, int incx, double *dy, int incy) {

    parallel_for(blocked_range<size_t>(0, n),
        [=](const blocked_range<size_t> & r) {
            for (size_t i = r.begin(); i < r.end(); i++) {
                dy[i] += da*dx[i];
            }
        }
    );

    return 0;
}
```

**Comment by kboyarinov** [comment] 2024-01-26 13:14
@mabalenk, regarding the first question, the compilation issues is caused by the following:

Consider the lambda you provided as a body to `parallel_for`:
```
[=](const blocked_range<size_t> & r) {
            for (size_t i = r.begin(); i < r.end(); i++) {
                dx[i] = distr(gen);
            }
        }
```
It is equivalent to providing the following callable object as a body

```
struct ParallelForBody {
    // Copies since lambda captures everything by value
    double* dx;
    std::uniform_real_distribution distr;
    std::mt19937 gen;
    
    void operator()(const blocked_range<size_t>& r) const {
        // ...
        dx[i] = distr(gen);
    }
};

```

And calling `distr(gen)` results in the call to `std::uniform_real_distribution::operator()` which [is non-const](https://en.cppreference.com/w/cpp/numeric/random/uniform_real_distribution/operator()). And since the `operator()` in the body class is marked as const (and required to be const by the TBB specification) - it is prohibited to call non-const methods of the distribution inside of the class.

Regarding the second part, in the changed code snipped device, generator and distribution would be created each time the body would be called and you will have the amount of devices, generators and distributions equivalent to the number of calls to the body object (and it is not guaranteed that some calls would not be done by the same thread). Consider solution proposed [here](https://stackoverflow.com/questions/21237905/how-do-i-generate-thread-safe-uniform-random-numbers) to minimize creation of "heavy" generator object each time.

Feel free to ask if you have any further questions.

**Comment by kboyarinov** [comment] 2024-02-01 16:32
@mabalenk, I will close this issue now. 
If you would have any further questions, don't hesitate to reopen this issue or create another one.

**Closed by kboyarinov** 2024-02-01 16:32 UTC
Labels: question
